
/*
 * This file is part of the Konsserto package.
 *
 * (c) Jessym Reziga <jessym@konsserto.com>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */
var Exception, InvalidArgumentException,
  __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

Exception = use('@Konsserto/Component/Debug/Exception');

InvalidArgumentException = (function(_super) {
  __extends(InvalidArgumentException, _super);

  function InvalidArgumentException() {
    return InvalidArgumentException.__super__.constructor.apply(this, arguments);
  }

  return InvalidArgumentException;

})(Exception);

module.exports = InvalidArgumentException;
