###
 * This file is part of the Konsserto package.
 *
 * (c) Jessym Reziga <jessym@konsserto.com>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
###


#
# Exception is maybe a mistake...
#
# @author Jessym Reziga <jessym@konsserto.com>
#
class Exception extends Error


  # Class constructor
  # @param {String} message Message (title) to display, default is 'Exception thrown'
  # @param {String} level Level of the exception
  # @param {String} htmlMessage HTML message to display
  # @param {String} toString The to String value of the exception (from the stack trace)
  constructor: (@message = 'Exception thrown', @level, @htmlMessage, @toString) ->
    @name = this.constructor.name

  # @param {String} name Name of the exception
  setName: (@name) ->
    return this

  # @param {String} level Level of the exception
  setLevel: (@level) ->
    return this

  # @param {String} message Message (title) of the exception
  setMessage: (@message) ->
    return this

  # @param {String} htmlMessage HTML message of the exception
  setHtmlMessage: (@htmlMessage) ->
    return this

  # @param {String} toString toString value returned of the exception
  setToString: (@toString) ->
    return this

  # @return {String} The name of the exception
  getName: () ->
    return @name

  # @return {String} The level of the exception
  getLevel: () ->
    return @level

  # @return {String} The message (title) of the exception
  getMessage: () ->
    return @message

  # @return {String} The HTML message of the exception
  getHtmlMessage: () ->
    return @htmlMessage

  # @return {String} toString value of the exception
  toString: () ->
    return @toString

##
# why ? inheritance doesn't work as expected ?
# Exception.prototype = new Error()
##
module.exports = Exception;